### ISSUE TITLE
Use engine components and compare with local LDB knowledge base

### ISSUE THREAD

**Issue by cuiweining** [scanoss/engine#8]
Does the engine use the local LDB library for scanning? Is it a problem? There is also why the source file is dug into the ldb, and the corresponding data information cannot be scanned when the scanoss is executed?

I have studied for a long time, but I haven't reached a conclusion. I hope to get answers here!

I used engine steps and results：

cwn:~/desktop/minr-master$ minr -d rugged,pigz,1.1.1,,, -u https://github.com/cuiweining/rugged/archive/refs/tags/v1.1.1.zip
cwn:~/desktop/minr-master$ minr -z mind
cwn:~/desktop/minr-master$ minr -i mined/
cwn:~/desktop/minr-master$ scanoss /home/cwn/desktop/gitFile/rugged-master.zip
{
  "/home/cwn/desktop/gitFile/rugged-master.zip": [
    {
      "id": "none",
      "server": {
        "hostname": "cwn-Aspire-F5-572G",
        "version": "4.2.8",
        "flags": "0",
        "elapsed": "0.045643s"
      }
    }
  ]
}
cwn:~/desktop/minr-master$ scanoss /home/cwn/desktop/gitFile/rugged-master/test/blob_test.rb
{
E063 Table /var/lib/ldb/oss/purl does not exist

**Comment by cuiweining** [comment]
This is log file output, how can I solve it?
log：
Checking entire file
8199544d22a76373e3a037447973cdf7 selected
Starting match: url
Incomplete metadata for (null)
Metadata is incomplete: ,,,
URL recordset contains 1 records
Final match: url
0 matches compiled:
Starting post-scan analysis
Match output starts

**Comment by scanoss-cs** [comment]
We are about to push a fix to this. The problem is that the engine expects certain tables, which should not be mandatory.

**Comment by mscasso-scanoss** [comment]
Hi @cuiweining , We have pushed a commit to master with the fix. Would you so kind to test and then close the ISSUE or let us know?

**Comment by cuiweining** [comment]
> 嗨@cuiweining，我们已经通过修复推送了对掌握的提交。你能测试一下然后关闭问题或让我们知道吗？

Hello, I reinstalled the engine, and then executed the test process, and found that the previous problem was still the same. Is there something wrong with my steps?

**Comment by mscasso-scanoss** [comment]
Have you done a pull or clone from master? Are you still having this error?  **E063 Table /var/lib/ldb/oss/purl does not exist**

**Comment by cuiweining** [comment]
> 你有没有从主人那里拉取或克隆？你还有这个错误吗？ **E063 表 /var/lib/ldb/oss/purl 不存在**
> 
> 抱歉，我说的是“引擎”存储库。

**Comment by cuiweining** [comment]
> > 你有没有从主人那里拉取或克隆？你还有这个错误吗？**E063表的/ var / lib中/ LDB / OSS /金银丝不存在**
> > 抱歉，我说是“引擎”存储库。

This error is gone, the current situation is not to report this error, but other conditions have not changed.

**Comment by mscasso-scanoss** [comment]
I have found your problem. You need to declare all the keys (Expected vendor,component,version,release_date,license,purl) when you are mining. Otherwise you don't get an error, but the scanning wont work properly. I'm going to correct the documentation and the error message both. In the mean time you can try the command:

```
minr -d cuiweinig,rugged,1.1.1,23/09,your_license,pkg:your_purl -u https://github.com/cuiweining/rugged/archive/refs/tags/v1.1.1.zip

minr -i mined

scanoss /home/cwn/desktop/gitFile/rugged-master.zip
```

Also, you can unzip and scan all files in the folder.

**Comment by cuiweining** [comment]
> ```
> scanoss /home/cwn/desktop/gitFile/rugged-master.zip
> ```
I tested the command you gave below and found that the result is still the same. Does the parameter after -d have to be accurate?
{
  "/home/cwn/desktop/gitFile/rugged-master.zip": [
    {
      "id": "none",
      "server": {
        "hostname": "cwn-Aspire-F5-572G",
        "version": "4.2.9",
        "flags": "0",
        "elapsed": "0.012121s"
      }
    }
  ]
}

**Comment by cuiweining** [comment]
Oh, I suddenly found that I can scan the file information in the zip package, but scanning the package is ineffective.

**Comment by cuiweining** [comment]
Thank you very much for your answers, it is indeed the scanning problem caused by the parameter problem. You can rest. Due to the jet lag, you should be late there. I'm very sorry for taking up your rest time. I have closed isssue now.
